https://codeforces.com/group/ZYtSoyvo86/contest/256788/problem/L  (swiss contar bits en rango)
https://codeforces.com/contest/762/problem/E  (lazy creation + ordenar quries)
https://codeforces.com/contest/1721/problem/D  (bits + sort)
https://codeforces.com/gym/101666/attachments (problema E MIS maximal independent set)
https://codeforces.com/contest/475/problem/D  (complejidad interesante)